-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 15:21:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `UserID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RobotRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RobotRoles` ;

CREATE TABLE IF NOT EXISTS `RobotRoles` (
  `RobotRoleID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotRole` VARCHAR(45) NULL DEFAULT 'ENUM'[Role1, Role2],
  `UserID` INT UNSIGNED NOT NULL,
  `AIResponseID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotRoleID`),
  CONSTRAINT `FK_RobotRole_UserID`
    FOREIGN KEY ()
    REFERENCES `Users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RobotModels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RobotModels` ;

CREATE TABLE IF NOT EXISTS `RobotModels` (
  `RobotModelID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Model` VARCHAR(45) NULL DEFAULT 'ENUM'[Model1, Model2],
  `ManufacturerID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotModelID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Technicians`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Technicians` ;

CREATE TABLE IF NOT EXISTS `Technicians` (
  `TechnicianID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TechnicianID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DeploymentLocations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DeploymentLocations` ;

CREATE TABLE IF NOT EXISTS `DeploymentLocations` (
  `DeploymentLocationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TechnicianID` INT UNSIGNED NULL,
  `ChargingSessionID` INT UNSIGNED NOT NULL,
  `EnvironmentType` VARCHAR(45) NOT NULL DEFAULT 'ENUM["HOME","HOSPITAL","WAREHOUSE"."FACTORY"],
  PRIMARY KEY (`DeploymentLocationID`),
  INDEX `FK_DeploymentLocations_TechnicianID_idx` (`TechnicianID` ASC) VISIBLE,
  CONSTRAINT `FK_DeploymentLocations_TechnicianID`
    FOREIGN KEY (`TechnicianID`)
    REFERENCES `Technicians` (`TechnicianID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SoftwareVersion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SoftwareVersion` ;

CREATE TABLE IF NOT EXISTS `SoftwareVersion` (
  `SoftwareVersionID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SoftwareVersionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Robots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Robots` ;

CREATE TABLE IF NOT EXISTS `Robots` (
  `RobotID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ChargingStationID` INT UNSIGNED NOT NULL,
  `RobotRoleID` INT UNSIGNED NOT NULL,
  `RobotModelID` INT UNSIGNED NOT NULL,
  `DeploymentLocationID` INT UNSIGNED NULL,
  `AlertID` INT UNSIGNED NOT NULL,
  `UserID` INT UNSIGNED NOT NULL,
  `SoftwareVersionID` INT UNSIGNED NOT NULL,
  `PerformanceMetricID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`RobotID`),
  INDEX `FK_Robot_DeploymentLocationID_idx` (`DeploymentLocationID` ASC) VISIBLE,
  CONSTRAINT `FK_Robot_RobotRoleID`
    FOREIGN KEY ()
    REFERENCES `RobotRoles` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_RobotModelID`
    FOREIGN KEY ()
    REFERENCES `RobotModels` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Robot_DeploymentLocationID`
    FOREIGN KEY (`DeploymentLocationID`)
    REFERENCES `DeploymentLocations` (`DeploymentLocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_SoftwareVersionID`
    FOREIGN KEY ()
    REFERENCES `SoftwareVersion` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Robot_UserID`
    FOREIGN KEY ()
    REFERENCES `Users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alerts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alerts` ;

CREATE TABLE IF NOT EXISTS `Alerts` (
  `AlertID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `Severity` VARCHAR(45) NOT NULL DEFAULT 'ENUM'[Model1, Model2],
  `TimeStamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`AlertID`),
  CONSTRAINT `FK_Alert_RobotID`
    FOREIGN KEY ()
    REFERENCES `Robots` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

CREATE TABLE IF NOT EXISTS `table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ``
-- -----------------------------------------------------
DROP TABLE IF EXISTS `` ;

CREATE TABLE IF NOT EXISTS `` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PerformanceMetrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PerformanceMetrics` ;

CREATE TABLE IF NOT EXISTS `PerformanceMetrics` (
  `PerformanceMetricID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RobotID` INT UNSIGNED NOT NULL,
  `MetricType` VARCHAR(45) NOT NULL,
  `MetricValue` INT UNSIGNED NOT NULL,
  `TimeStamp` DATETIME NOT NULL,
  PRIMARY KEY (`PerformanceMetricID`),
  INDEX `FK_PerformanceMetrics_RobotID_idx` (`RobotID` ASC) VISIBLE,
  CONSTRAINT `FK_PerformanceMetrics_RobotID`
    FOREIGN KEY (`RobotID`)
    REFERENCES `Robots` (`RobotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
